"""shares

Revision ID: 3bedc782f041
Revises: ce67fe216100
Create Date: 2026-05-13 20:32:59.162372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bedc782f041'
down_revision: Union[str, Sequence[str], None] = 'ce67fe216100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('trust_score', sa.Integer(), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=False),
    sa.Column('eth_price', sa.Float(), nullable=False),
    sa.Column('sol_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_shares_messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('processed_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('users_shares',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('shares_broker', sa.String(), nullable=False),
    sa.Column('broker_commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('exchange')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('exchange_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('trust_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('btc_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('eth_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('sol_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exchange_pkey'))
    )
    op.drop_table('users_shares')
    op.drop_table('user_shares_messages')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
