"""shares

Revision ID: 41274de60c46
Revises: ce67fe216100
Create Date: 2026-05-14 22:05:45.183495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41274de60c46'
down_revision: Union[str, Sequence[str], None] = 'ce67fe216100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_shares_messages',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('processed_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('users_shares',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('shares_broker', sa.String(), nullable=False),
    sa.Column('broker_commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_shares')
    op.drop_table('user_shares_messages')
    # ### end Alembic commands ###
