"""init exchange table

Revision ID: aef2e3784b14
Revises: 
Create Date: 2026-02-19 21:04:34.114006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef2e3784b14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('work_in_russia', sa.Boolean(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('owner_first_name', sa.String(), nullable=False),
    sa.Column('owner_last_name', sa.String(), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=True),
    sa.Column('eth_price', sa.Float(), nullable=True),
    sa.Column('sol_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    # ### end Alembic commands ###
