"""create_exchange_table

Revision ID: ce67fe216100
Revises: 
Create Date: 2026-03-01 22:07:58.429437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce67fe216100'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('exchange_name', sa.String(), nullable=False),
    sa.Column('trust_score', sa.INTEGER(), nullable=False),
    sa.Column('btc_price', sa.Float(), nullable=False),
    sa.Column('eth_price', sa.Float(), nullable=False),
    sa.Column('sol_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchange')
    # ### end Alembic commands ###
